# Generated by Django 4.1.8 on 2023-05-02 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("referrals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userreferral",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userreferral",
            name="invite_code",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="userreferral",
            name="invited_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referred_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
