# Generated by Django 4.1.8 on 2023-05-03 04:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("referrals", "0004_referralearning"),
    ]

    operations = [
        migrations.RenameField(
            model_name="referralearning",
            old_name="created",
            new_name="date_earned",
        ),
        migrations.RenameField(
            model_name="referralearning",
            old_name="from_user",
            new_name="source",
        ),
    ]
