# Generated by Django 4.1.8 on 2023-04-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="karma",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="karma"
            ),
        ),
    ]
