# Generated by Django 4.1.8 on 2023-05-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_first_name_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Users Last Name"
            ),
        ),
    ]
