# Generated by Django 4.1.8 on 2023-04-29 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pathlib
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="World",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Name of User"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(choices=[("CAT-1", "CAT-1")], max_length=50),
                ),
                (
                    "visibility",
                    models.BooleanField(default=False, verbose_name="visibility"),
                ),
                (
                    "source_path",
                    models.FilePathField(
                        path=pathlib.PureWindowsPath(
                            "C:/Users/WRASH-TECH/Documents/Tech-Project/Web/Django/Yeager/yeag_sliper/yeager_ai/jsonworld"
                        )
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
